apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws-ic
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: cluster-host-apache
      http:
        paths:
          - path: /tools/dt-ic
            pathType: "Prefix"
            backend:
              service:
                name: aws-ic
                port:
                  number: 80
    - host: advisor.dev.aws.jpmchase.net
      http:
        paths:
          - path: /tools/dt-ic
            pathType: "Prefix"
            backend:
              service:
                name: aws-ic
                port:
                  number: 80
    - host: blue.advisor.dev.aws.jpmchase.net
      http:
        paths:
          - path: /tools/dt-ic
            pathType: "Prefix"
            backend:
              service:
                name: aws-ic
                port:
                  number: 80
  tls:
    - hosts:
        - advisor.dev.aws.jpmchase.net
        - blue.advisor.dev.aws.jpmchase.net

