apiVersion: v1
kind: Service
metadata:
  name: aws-ic
  labels:
    app: aws-ic
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: aws-ic
