bases:
  - ../../base/
kind: Kustomization
metadata:
  name: kustomization

#images:
#  - name: app-image
#    newName: <+artifact.image>

#namespace: <+infra.namespace>

resources: 
- harness-patch-deployment.yaml
- harness-patch-hpa.yaml
- harness-patch-ingress.yaml
- harness-patch-service.yaml
- kustomization.yml

configMapGenerator:
  - name: aws-ic-runtime
    literals:
      - SPRING_PROFILES_ACTIVE=aws-dev, fake-auth, cloud
      - APP_FLAGS=-Dsun.net.http.allowRestrictedHeaders=true  -Djdk.tls.allowUnsafeServerCertChange=true -Dsun.security.ssl.allowUnsafeRenegotiation=true -Dserver.servlet.context-path=<+pipeline.stages.DeployDEV.variables.context_path>
